#runtime: custom
#env: flex

runtime: go116

app_engine_apis: true

instance_class: F1

automatic_scaling:
  max_instances: 0
  min_instances: 1
  min_idle_instances: 0

env_variables:
  ENVIRONMENT: "production"
  TELEGRAPH_TOKEN: ${TELEGRAPH_TOKEN}
  CWB_TOKEN: ${CWB_TOKEN}
  NEKOMAID_PIXIV_USERNAME: "${NEKOMAID_PIXIV_USERNAME}"
  NEKOMAID_PIXIV_PASSWORD: "${NEKOMAID_PIXIV_PASSWORD}"
  NEKOMAID_TINAMI_APIKEY: "${NEKOMAID_TINAMI_APIKEY}"
