#runtime: custom
#env: flex

runtime: go116

app_engine_apis: true

instance_class: F1

automatic_scaling:
  max_instances: 0
  min_instances: 1
  min_idle_instances: 0

env_variables:
  TELEGRAPH_TOKEN: