info:
  contact: {}
paths:
  /telegraph/news:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: 取得 Telegraph 文章列表
      tags:
      - Telegraph
swagger: "2.0"
