info:
  contact: {}
paths:
  /dmm/crawler:
    get:
      consumes:
      - application/json
      parameters:
      - description: DMM目標頁面網址
        in: query
        name: url
        required: true
        type: string
      - description: string enums
        enum:
        - video
        - actress
        in: query
        name: type
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: 使用 DMM 爬蟲爬出頁面指定資料
      tags:
      - DMM
  /telegraph/news:
    get:
      consumes:
      - application/json
      parameters:
      - description: 頁碼
        in: query
        name: page
        type: integer
      produces:
      - application/json
      responses: {}
      summary: 取得 Telegraph 文章列表
      tags:
      - Telegraph
swagger: "2.0"
